### ISSUE TITLE
Glyphs are sorted

### ISSUE THREAD

**Issue by hatchzo** [googlei18n/glyphs2ufo#10]
I think glyphs are sorted after glyphs2ufo conversion. I don't want to break the original glyph order Glyphs app file has.

**Comment by jamesgk** [comment]
I think what should be happening is that the original Glyphs order is used, and then if any glyphs are not included in that ordering they are appended to the UFO ordering, sorted by name. Is that OK?

See here:
https://github.com/googlei18n/glyphs2ufo/blob/a4809a43cdf01a76deadc7118b897ee9022fef8c/Lib/glyphs2ufo/torf.py#L109

**Comment by hatchzo** [comment]
OK... You mean, UFO file doesn't support an original glyph order data except ordering by name or unicode. Is that right?

**Comment by schriftgestalt** [comment]
Usually there is no explicit ordering list in a .glyphs file. The glyph order is defined by the order of the glyphs in the file. You can ignore the 'glyphOrder' parameter. It is used to sort the glyphs so it is redundant.

**Comment by schriftgestalt** [comment]
I have fixed it.

**Comment by hatchzo** [comment]
Georg, 
Do you suggest 'glyphOrder' parameter in .glyphs will be discontinue ?

**Comment by schriftgestalt** [comment]
No, but you don't need it to extract the order of the glyphs from the file.

**Comment by hatchzo** [comment]
I apologize to rehash this issue, Probably, I might not catch this discussion exactly. Has it be already fixed ? 
I made an original glyph order on .glyphs file and then converted to .ufo file. However, my order was ignored, glyphs were sorted by Alphabet or Unicode when the.ufo is opened on the app.

**Comment by jamesgk** [comment]
Right. According to @schriftgestalt the glyph order in the output UFO should be the order the glyphs appear in the .glyphs file; the glyphOrder element is not used.

**Comment by schriftgestalt** [comment]
Just to clarify: The glyphOrder is used internally to sort the glyphs. So the glyphOrder parameter should always be in sync (with two exceptions: if the glyphOrder contains names that are not in the font or if there are more glyphs in the font than entries in the list). So always use the order as found in the `Font.glyphs` array.

**Comment by hatchzo** [comment]
Thank you for your comments. I believe there is a chance of improvement.
