### ISSUE TITLE
parse module

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/glyphs2ufo#2]
I tried to get this to run but could not find anything about `from parser import Parser` (glyphslib.py:26).

**Comment by behdad** [comment]
Humm. you mean you don't have parser.py?

**Comment by anthrotype** [comment]
Maybe he's on python3 and the relative imports don't work unless explicitly defined with a dot?

**Comment by schriftgestalt** [comment]
I have, but I get an error. Maybe because there is a build in module with the same name? Or I installed it wrong. Silly of me not to see this.

**Comment by behdad** [comment]
Ah, makes more sense.

**Comment by behdad** [comment]
> I have, but I get an error. Maybe because there is a build in module with the same name? Or I installed it wrong. Silly of me not to see this.

How are you running it?

**Comment by schriftgestalt** [comment]
I’m on python 2.7. I renamed the parser.py file and now it works.

**Comment by behdad** [comment]
Right.  I'll change the relative imports.

**Comment by behdad** [comment]
Assigning to James to fix when he has time.
Also: https://github.com/googlei18n/glyphs2ufo/issues/4

**Comment by jamesgk** [comment]
This should be fixed by 5fa3543710724f1a28d40517b69276a50db98886
