### ISSUE TITLE
Does each glyph get its own group if the kerning group is unspecified?

### ISSUE THREAD

**Issue by behdad** [googlei18n/glyphs2ufo#23]
In a delivery we have received from Monotype, the glyphs source has kerning for a lot of groups, eg @MMK_R_ddhe-ethiopic, but no glyphs has "ddhe-ethiopic" as its rightKerningGroup.  In particular, the "ddhe-ethiopic" has no kerning groups defined for it.  Does that put the glyph in its own kerning class by default if no kerning class is specified?  That would explain a lot of warning we are seeing with this font. Georg, can you please clarify?

@schriftgestalt

**Comment by schriftgestalt** [comment]
If a glyph without classes is kerned with a class, it is put in class on its own. Otherwise I would need to decompose the class. In my experience that leads to a bigger GPOS tables and thus will cause subtable overflows 
earlier. 
What warnings do you get?

**Comment by behdad** [comment]
> If a glyph without classes is kerned with a class, it is put in class on its own. Otherwise I would need to decompose the class. In my experience that leads to a bigger GPOS tables and thus will cause subtable overflows earlier.

Thanks.  I'm not talking about what goes into the output font; rather, what's the semantics of the .glyphs source file.

> What warnings do you get?

Eg. I'm getting, from glyphs2ufo:
```
WARNING: Non-existent glyph class public.kern2.ddhe_ethiopic found in kerning rules.
```
Indeed, no glyph in the source has leftKerningGroup = ddhe-ethiopic, nor any rightKerningGroup = ddhe-ethiopic, yet both `"@MMK_L_ddhe-ethiopic"` and `"@MMK_R_ddhe-ethiopic"` appear in the kerning data.

So, my question is, if a glyph X does not specify rightKerningGroup, does it automatically belong to `"@MMK_L_X"` and if it does not have leftKerningGroup, does it automatically belong to `"@MMK_R_X"`?

Thanks.

**Comment by schriftgestalt** [comment]
That might happen if the glyphs had a class before and then the kerning would be attached to the class. It is not attached to a specific glyph, it just lives as an entry in the kerning list. If you remove the glyph or remove/change its group entries, the kerning values are left in the kerning list but should be ignored. It should be remove if you run a "Cleanup" from the Kerning Panel.

**Comment by behdad** [comment]
Ok, thanks.  So it *is* a source error.  Nothing need to change in
glyphs2ufo.

On Sun, Mar 27, 2016 at 2:26 PM, Georg Seifert <notifications@github.com>
wrote:

> That might happen if the glyphs had a class before and then the kerning
> would be attached to the class. It is not attached to a specific glyph, it
> just lives as an entry in the kerning list. If you remove the glyph or
> remove/change its group entries, the kerning values are left in the kerning
> list but should be ignored. It should be remove if you run a "Cleanup" from
> the Kerning Panel.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/glyphs2ufo/issues/23#issuecomment-202147807>
>



-- 
behdad
http://behdad.org/
