### ISSUE TITLE
Relax duplicate-kerning checks

### ISSUE THREAD

**Issue by behdad** [googlei18n/glyphs2ufo#24]
Now that https://github.com/unified-font-object/ufoLib/pull/21 is merged, we should update our checks as well.

Ideally, we should call defcon validator and only "resolve" the pairs that defcon is going to barf on.

Alternatively, hopefully https://github.com/typesupply/defcon/issues/38 will be fixed.

**Comment by jamesgk** [comment]
So, what to do if there is ambiguity? Should glyphs2ufo crash? Just warn? Not check for conflicts at all?

**Comment by behdad** [comment]
I think glyph2ufo should warn and generate equivalent of what Glyphs generates.  Now, recently, we heard from Monotype that different versions of Glyphs are inconsistent as to what effectively they generate.

**Comment by schriftgestalt** [comment]
Could you provide examples. I didn't change the kerning code in a long time so I'm courios what difference that might be.

**Comment by behdad** [comment]
> Could you provide examples. I didn't change the kerning code in a long time so I'm courios what difference that might be.

I'll try to see if I can get examples from them.

**Comment by behdad** [comment]
So, question at this point is, if there is a glyph0-class1 and a class0-glyph1 that both apply to the same pair glyph0-glyph1, and the two pairs have different kern values, and there is no kern pair defined for glyph0-glyph1, then which kern value *wins* in the binary generated by Glyphs?

**Comment by behdad** [comment]
> So, question at this point is, if there is a glyph0-class1 and a class0-glyph1 that both apply to the same pair glyph0-glyph1, and the two pairs have different kern values, and there is no kern pair defined for glyph0-glyph1, then which kern value wins in the binary generated by Glyphs?

@schriftgestalt Do you happen to know this off the top of your head?  Can you document it?  Monotype is telling us "you should do whatever Glyphs does, as that's what designers see."

**Comment by twardoch** [comment]
Here's is a small test.

# Situation 1
### Groups

```
@A = [A a];
@V = [V v];
```

### Kerning

```
@A @V -250
@A v -100
a @V 100
```

### Result in FEA

```
lookup GPOS_LOOKUP_00000 
{
    pos \A \v <0 0 -100 0>;
    pos \a \V <0 0 100 0>;
    pos \a \v <0 0 100 0>;
 subtable;
    pos @A @V <0 0 -250 0>;
} GPOS_LOOKUP_00000;
```

### Result in text
When the text is `AVAvaVav`, the result in both Glyphs and HarfBuzz is:
```
A V -250
A v -100
a V 100
a v 100
```

<img width="1521" alt="scr- 2016-04-21 at 22 23 40" src="https://cloud.githubusercontent.com/assets/519108/14723214/3395c7e2-0810-11e6-9882-341df8e2f8ea.PNG">

# Situation 2
### Groups

```
@A = [A a];
@V = [V v];
```

### Kerning

```
@A @V -250
@A v -100
a @V 100
A @V -400
```

### Result in FEA

```
lookup GPOS_LOOKUP_00000 
{
    pos \A \V <0 0 -400 0>;
    pos \A \v <0 0 -400 0>;
    pos \a \V <0 0 100 0>;
    pos \a \v <0 0 100 0>;
 subtable;
    pos @A @V <0 0 -250 0>;
} GPOS_LOOKUP_00000;

```

### Result in text
When the text is `AVAvaVav`, the result in both Glyphs and HarfBuzz is:
```
A V -400
A v -400
a V 100
a v 100
```

<img width="1513" alt="scr- 2016-04-21 at 22 40 29" src="https://cloud.githubusercontent.com/assets/519108/14723605/39df9720-0812-11e6-817f-beecfbf39004.PNG">

**Comment by behdad** [comment]
Thanks @twardoch  incredibly useful!  Can you contribute your .glyphs file to the project to add as a test?

So, it's either that the glyph-class wins, or that it's arbitrary based on what is sorted after what.  Can you investigate a bit more?  Perhaps because '@' sorts before the letters, the group-glyph is always processed before glyph-group?  Can you reject that assumption?  Using .notdef perhaps?

I wish @typesupply accepted my suggestion to make glyph-class override class-glyph in UFO, but he didn't like it.

**Comment by twardoch** [comment]
I've amended my reply above with another situation, and added a ZIP with the test files.

**Comment by twardoch** [comment]
For the `AV` text pair, it seems that Glyphs goes in this order. If it finds a match, it takes it, if not, it continues: 
1. `A V`
2. `A @V`
3. `@A V`
4. `@A @V`

Which is actually logical — for any text pair, it first tries to find the “most specific match” for the 1st glyph in the pair, and then, the most specific match for the 2nd glyph in the pair. 

So it looks to me that the generalized order of processing is: 
1. `glyph1 glyph2`
2. `glyph1 @group2`
3. `@group1 glyph2`
4. `@group1 @group2`

**Comment by typesupply** [comment]
> I wish @typesupply accepted my suggestion to make glyph-class override class-glyph in UFO, but he didn't like it.

I'm still thinking! I have a day job and a ton of code stuff to think about.

**Comment by behdad** [comment]
> Which is actually logical — for any text pair, it first tries to find the “most specific match” for the 1st glyph in the pair, and then, the most specific match for the 2nd glyph in the pair.

That's how I logicalized it to myself as well ;)

**Comment by behdad** [comment]
> I wish @typesupply accepted my suggestion to make glyph-class override class-glyph in UFO, but he didn't like it.
> 
> I'm still thinking! I have a day job and a ton of code stuff to think about.

Great to know!  Thanks.  Just to clarify, when I file issues, it's to document them.  By no means feel like *you* have to fix it.  If you agree on principle, one of us will happily send a PR.

**Comment by schriftgestalt** [comment]
I had a look at the code.
It goes through all pairs in the order you see in the kerning panel. What it does is to produce two dicts, one with the class to class kerning and one with the glyph to glyph pairs (and flattened classes if needed). 
In case of AV2, it first adds the pairs A v -100 and a v -100 from the @A v pair you see in the .glyphs file. Then it parses the rest of the list and those praise overwrite the once already in the list. So the last in the list wins.

**Comment by behdad** [comment]
Thanks @schriftgestalt!  So the order is significant after all.  I think we can implement this.

**Comment by twardoch** [comment]
Yeah. So, @schriftgestalt, would you say that in terms of FEA code generation, you’d do the following: 

1. Expand all “class-to-glyph” pairs and store into a flat list. 
2. Expand all “glyph-to-class” pairs and add to the previous list, overwriting entries where both glyphs are the same.
3. Take all “glyph-to-glyph” pairs and add it to the previous list, overwriting entries where both glyphs are the same. Write the result into the 1st subtable. 
4. Write all class-to-class pairs in the 2nd subtable. 

Right?

**Comment by behdad** [comment]
> It goes through all pairs in the order you see in the kerning panel.

So I think the question is, what is that order?  Is it plain sorted list?

**Comment by schriftgestalt** [comment]
> Yeah. So, @schriftgestalt, would you say that in terms of FEA code generation, you do the following:

> Expand all “class-to-glyph” pairs and store into a flat list.
Expand all “glyph-to-class” pairs and add to the previous list, overwriting entries where both glyphs are the same.
> Take all “glyph-to-glyph” pairs and add it to the previous list, overwriting entries where both glyphs are the same. Write the result into the 1st subtable.
> Write all class-to-class pairs in the 2nd subtable.
> Right?

No. IT goes through the list of pairs and if it finds a pair that includes on glyph, and a class, it flattens the class and puts all pairs in the glyphs pair list. 

The two list are actually nested dicts. That way new values overwrite old once.

> So I think the question is, what is that order? Is it plain sorted list?
The kerning is stores in an 'Ordered Dict'. So it will use the order as it is in the file. There is no ordering on kern feature generation or anywhere else.

**Comment by twardoch** [comment]
Hmm, I’m looking at it in Glyphs, and I don’t know **how** Glyphs sorts the Kerning panel. I mean, first it sorts the “1st side” (groups or glyphs) somehow, and within the “1st side” entries, it makes “2nd side” entries (groups or glyphs). But I have no idea how Glyphs determines the order of sorting within each side. 

I just arrived at this: 
<img width="324" alt="scr- 2016-04-22 at 00 05 27" src="https://cloud.githubusercontent.com/assets/519108/14725722/f6885136-081d-11e6-9b09-294c089db71f.PNG">

Doesn’t matter so much how I did it and whether it makes logical sense — it’s very unclear to me what is the order by which this hierarchy is arranged. I hope @schriftgestalt can clarify. :)

**Comment by schriftgestalt** [comment]
The order is like this:
```
@A V -400
@A @One -100
@V @A -10
@one @one -44
@one @One -66
...
```

**Comment by twardoch** [comment]
This may be off-topic, but where does this order come from? :)

**Comment by schriftgestalt** [comment]
Mostly from the order of adding the pairs.

**Comment by twardoch** [comment]
Ah, OK. That seems consistent with my experiment, thanks!
