### ISSUE TITLE
Linebreaks

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/glyphs2ufo#25]
Dave and others asked me a few times to improve the file structure of glyphs files to be better subtable to deal with version control. It was mostly about the feature code being put in one line. 

I made some experiments and plist can have multiple lines in a string after all. I implemented this in my parsing code and added a (yet hidden) custom parameter that would prevent the escaping of newlines. This is not ready for production yet and will not be used by normal people for some time, just to let you know.

Do you have strong objections about this?

**Comment by jamesgk** [comment]
This sounds good to me.

**Comment by schriftgestalt** [comment]
The current parser does not support this. So it would need some work.

**Comment by jamesgk** [comment]
Sure. I can work on that, could you provide an example source file?

**Comment by schriftgestalt** [comment]
Just replace \012 with \n in any file that has feature code.
